name: "Build"
on:
  pull_request:
  push:
strategy:
  matrix:
    jobset:
      - hello
      - python
      - r

runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2.3.4
    with:
      persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
      fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
  - uses: cachix/install-nix-action@v13
  - uses: cachix/cachix-action@v10
    with:
      name: tbenst
      # If you chose signing key for write access
      signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
  - name: build
    run: nix-build jobsets/${{ matrix.jobset }}.nix